// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=repository/interfaces.go -destination=repository/interfaces.mock.gen.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateEstate mocks base method.
func (m *MockRepositoryInterface) CreateEstate(ctx context.Context, input CreateEstateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEstate", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEstate indicates an expected call of CreateEstate.
func (mr *MockRepositoryInterfaceMockRecorder) CreateEstate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEstate", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateEstate), ctx, input)
}

// CreateTree mocks base method.
func (m *MockRepositoryInterface) CreateTree(ctx context.Context, input CreateTreeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTree", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTree indicates an expected call of CreateTree.
func (mr *MockRepositoryInterfaceMockRecorder) CreateTree(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTree", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateTree), ctx, input)
}

// EstateExists mocks base method.
func (m *MockRepositoryInterface) EstateExists(ctx context.Context, estateID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstateExists", ctx, estateID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstateExists indicates an expected call of EstateExists.
func (mr *MockRepositoryInterfaceMockRecorder) EstateExists(ctx, estateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstateExists", reflect.TypeOf((*MockRepositoryInterface)(nil).EstateExists), ctx, estateID)
}

// GetDronePlanSummary mocks base method.
func (m *MockRepositoryInterface) GetDronePlanSummary(ctx context.Context, estateID string) (DronePlanSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDronePlanSummary", ctx, estateID)
	ret0, _ := ret[0].(DronePlanSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDronePlanSummary indicates an expected call of GetDronePlanSummary.
func (mr *MockRepositoryInterfaceMockRecorder) GetDronePlanSummary(ctx, estateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDronePlanSummary", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDronePlanSummary), ctx, estateID)
}

// GetTestById mocks base method.
func (m *MockRepositoryInterface) GetTestById(ctx context.Context, input GetTestByIdInput) (GetTestByIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestById", ctx, input)
	ret0, _ := ret[0].(GetTestByIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestById indicates an expected call of GetTestById.
func (mr *MockRepositoryInterfaceMockRecorder) GetTestById(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTestById), ctx, input)
}

// GetTreeStats mocks base method.
func (m *MockRepositoryInterface) GetTreeStats(ctx context.Context, estateID string) (TreeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreeStats", ctx, estateID)
	ret0, _ := ret[0].(TreeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreeStats indicates an expected call of GetTreeStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetTreeStats(ctx, estateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreeStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTreeStats), ctx, estateID)
}

// TreeExists mocks base method.
func (m *MockRepositoryInterface) TreeExists(ctx context.Context, estateID string, x, y int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeExists", ctx, estateID, x, y)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeExists indicates an expected call of TreeExists.
func (mr *MockRepositoryInterfaceMockRecorder) TreeExists(ctx, estateID, x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeExists", reflect.TypeOf((*MockRepositoryInterface)(nil).TreeExists), ctx, estateID, x, y)
}
